# CalculiX adapter
[[imports]]
path = "github.com/precice/calculix-adapter"

  [[imports.mounts]]
  source = "docs/adapter-calculix-overview.md"
  target = "content/docs/adapters/calculix/_index.md"

  [[imports.mounts]]
  source = "docs"
  target = "content/docs/adapters/calculix"
  files = ["! adapter-calculix-overview.md"]

# code_aster adapter
[[imports]]
path = "github.com/precice/code_aster-adapter"

  [[imports.mounts]]
  source = "docs/adapter-code_aster.md"
  target = "content/docs/adapters/code_aster/_index.md"

  [[imports.mounts]]
  source = "docs/images"
  target = "content/docs/adapters/code_aster/images"

# deal.II adapter
[[imports]]
path = "github.com/precice/dealii-adapter"

  [[imports.mounts]]
  source = "docs/overview.md"
  target = "content/docs/adapters/dealii/_index.md"

  [[imports.mounts]]
  source = "docs"
  target = "content/docs/adapters/dealii"
  files = ["! overview.md"]

# DuMuX adapter
[[imports]]
path = "github.com/precice/dumux-adapter"

  [[imports.mounts]]
  source = "docs/overview.md"
  target = "content/docs/adapters/dumux/_index.md"

  [[imports.mounts]]
  source = "docs"
  target = "content/docs/adapters/dumux"
  files = ["! overview.md"]

# DUNE adapter
[[imports]]
path = "github.com/precice/dune-adapter"

  [[imports.mounts]]
  source = "docs/overview.md"
  target = "content/docs/adapters/dune/_index.md"

# FEniCS adapter
[[imports]]
path = "github.com/precice/fenics-adapter"

  [[imports.mounts]]
  source = "docs/adapter-fenics.md"
  target = "content/docs/adapters/fenics/_index.md"

  [[imports.mounts]]
  source = "docs"
  target = "content/docs/adapters/fenics"
  files = ["! adapter-fenics.md", "! ReleaseGuide.md"]

# FEniCSx adapter
[[imports]]
path = "github.com/precice/fenicsx-adapter"

  [[imports.mounts]]
  source = "docs/README.md"
  target = "content/docs/adapters/fenicsx/_index.md"

# OpenFOAM adapter
[[imports]]
path = "github.com/precice/openfoam-adapter"

  [[imports.mounts]]
  source = "docs/README.md"
  target = "content/docs/adapters/openfoam/_index.md"

  [[imports.mounts]]
  source = "docs"
  target = "content/docs/adapters/openfoam"
  files = ["! README.md", "! images/docs-adapter-openfoam-implicit-loop-src.md"]

# SU2 adapter
[[imports]]
path = "github.com/precice/su2-adapter"

  [[imports.mounts]]
  source = "docs/overview.md"
  target = "content/docs/adapters/su2/_index.md"

  [[imports.mounts]]
  source = "docs"
  target = "content/docs/adapters/su2"
  files = ["! overview.md"]

# ASTE
[[imports]]
path = "github.com/precice/aste"

  [[imports.mounts]]
  source = "docs/README.md"
  target = "content/docs/tooling/aste/_index.md"

# FMI runner
[[imports]]
path = "github.com/precice/fmi-runner"

  [[imports.mounts]]
  source = "docs/README.md"
  target = "content/docs/tooling/fmi-runner/_index.md"

  [[imports.mounts]]
  source = "docs/images"
  target = "content/docs/tooling/fmi-runner/images"

# Micro Manager
[[imports]]
path = "github.com/precice/micro-manager"

  [[imports.mounts]]
  source = "docs/README.md"
  target = "content/docs/tooling/micro-manager/_index.md"

  [[imports.mounts]]
  source = "docs"
  target = "content/docs/tooling/micro-manager"
  files = ["! README.md", "! ReleaseGuide.md"]

# preECO guidelines
[[imports]]
path = "github.com/precice/preeco-orga"

  [[imports.mounts]]
  source = "guidelines/guidelines-adapters.md"
  target = "content/community/contribute/guidelines/_index.md"

  [[imports.mounts]]
  source = "guidelines"
  target = "content/community/contribute/guidelines"
  files = ["! guidelines-adapters.md"]

# This file is automatically generated by tools/sync_tutorials.py

