[build]
  command = "sed -i '/github.com\\/precice\\/tutorials/d' go.sum && GOFLAGS=\"-mod=mod\" hugo --gc --minify"
  publish = "public"
[build.environment]
  GOPROXY = "https://proxy.golang.org,direct"
  GONOSUMDB = "github.com/precice/tutorials,github.com/precice/code_aster-adapter"
