[build]
  command = "hugo --gc --minify"
  publish = "public"
[build.environment]
  GO_VERSION = "1.26.3"
  HUGO_VERSION = "0.163.3"
  GOPROXY = "https://proxy.golang.org,direct"
  GONOSUMDB = "github.com/precice/tutorials,github.com/precice/code_aster-adapter"
