#!/usr/bin/env python3
"""
sync_tutorials.py

Automates the synchronization of tutorial metadata from the precice/tutorials
repository into the precice.github.io Hugo website.

This script fetches the latest `master` branch directory tree from GitHub, 
generates the Hugo Module mounts required to serve the tutorials, and keeps the
Hugo website's top-level tutorial navigation alphabetized.

Usage:
  python3 tools/sync_tutorials.py --module-toml config/_default/module.toml --sidebar-yaml data/sidebars/tutorial_sidebar.yml
"""

import urllib.request
import json
import yaml
import os
import argparse
import logging
import sys

def setup_logging():
    logging.basicConfig(
        level=logging.INFO,
        format="[%(levelname)s] %(message)s"
    )

def fetch_github_tree(repo: str = "precice/tutorials", branch: str = "master") -> dict:
    url = f"https://api.github.com/repos/{repo}/git/trees/{branch}?recursive=1"
    req = urllib.request.Request(url)
    req.add_header("User-Agent", "precice-hugo-sync")
    
    try:
        logging.info(f"Fetching directory tree from {url}")
        with urllib.request.urlopen(req) as response:
            return json.loads(response.read())
    except Exception as e:
        logging.error(f"Failed to fetch from GitHub API: {e}")
        sys.exit(1)

def discover_tutorials(tree_data: dict) -> tuple[set[str], set[str]]:
    directories_with_readme = set()
    directories_with_images = set()

    for item in tree_data.get("tree", []):
        path = item["path"]
        if path.endswith("/README.md"):
            folder = os.path.dirname(path)
            # Only consider top-level directories to avoid nesting
            if folder and "/" not in folder and folder != "tools":
                directories_with_readme.add(folder)
        elif path.endswith("/images") and item["type"] == "tree":
            directories_with_images.add(path)
            
    return directories_with_readme, directories_with_images

def generate_module_toml(
    toml_path: str, 
    tutorials: set[str], 
    images: set[str], 
    repo_path: str = "github.com/precice/tutorials"
):
    try:
        with open(toml_path, "r") as f:
            lines = f.readlines()
    except Exception as e:
        logging.error(f"Failed to read existing toml file: {e}")
        sys.exit(1)

    marker = "# This file is automatically generated by tools/sync_tutorials.py"
    base_lines = []
    for line in lines:
        if marker in line:
            break
        base_lines.append(line.rstrip())

    # Ensure exactly one blank line before the marker
    while base_lines and not base_lines[-1].strip():
        base_lines.pop()
    base_lines.append("")

    toml_lines = base_lines + [
        marker,
        "[[imports]]",
        f'path = "{repo_path}"',
        ""
    ]
    
    for folder in sorted(tutorials):
        toml_lines.append("  [[imports.mounts]]")
        toml_lines.append(f'  source = "{folder}/README.md"')
        toml_lines.append(f'  target = "content/tutorials/{folder}/_index.md"')
        toml_lines.append("")
        
        if f"{folder}/images" in images:
            toml_lines.append("  [[imports.mounts]]")
            toml_lines.append(f'  source = "{folder}/images"')
            toml_lines.append(f'  target = "content/tutorials/{folder}/images"')
            toml_lines.append("")
            
    # Always mount the system tests explicitly
    toml_lines.append("  [[imports.mounts]]")
    toml_lines.append('  source = "tools/tests/README.md"')
    toml_lines.append('  target = "content/docs/dev-docs/system-tests/_index.md"')
    toml_lines.append("")

    try:
        with open(toml_path, "w") as f:
            f.write("\n".join(toml_lines))
        logging.info(f"Updated {toml_path} with {len(tutorials)} tutorial mounts.")
    except Exception as e:
        logging.error(f"Failed to write toml file: {e}")
        sys.exit(1)

def update_sidebar_yaml(yaml_path: str, tutorials: set[str]):
    try:
        with open(yaml_path, "r") as f:
            sidebar = yaml.safe_load(f)
    except Exception as e:
        logging.error(f"Failed to read sidebar yaml: {e}")
        sys.exit(1)

    existing_urls = set()
    for entry in sidebar.get("entries", []):
        for folder in entry.get("folders", []):
            for item in folder.get("folderitems", []):
                if "url" in item:
                    existing_urls.add(item["url"])
                for subfolder in item.get("subfolders", []):
                    for subitem in subfolder.get("subfolderitems", []):
                        if "url" in subitem:
                            existing_urls.add(subitem["url"])

    new_blocks = []
    for folder in sorted(tutorials):
        expected_url = "/quickstart.html" if folder == "quickstart" else f"/tutorials-{folder}.html"
        
        if expected_url not in existing_urls:
            formatted_title = folder.replace("-", " ").capitalize()
            # Generate the YAML block manually to preserve the existing formatting.
            block = f"    - title: {formatted_title}\n"
            block += f"      url: {expected_url}\n"
            block += "      output: web, pdf\n\n"
            new_blocks.append(block)
            existing_urls.add(expected_url)
            logging.info(f"Queued missing tutorial for sidebar: {formatted_title}")
            
    if new_blocks:
        try:
            with open(yaml_path, "r") as f:
                lines = f.readlines()

            all_tutorials_start = next(
                (index for index, line in enumerate(lines)
                 if line.rstrip() == "  - title: All tutorials"),
                None,
            )
            if all_tutorials_start is None:
                raise ValueError("Could not find the 'All tutorials' sidebar section")

            section_end = next(
                (index for index in range(all_tutorials_start + 1, len(lines))
                 if lines[index].startswith("  - title: ")),
                len(lines),
            )
            item_starts = [
                index for index in range(all_tutorials_start + 1, section_end)
                if lines[index].startswith("    - title: ")
            ]
            if not item_starts:
                raise ValueError("The 'All tutorials' sidebar section has no tutorial items")

            item_start = item_starts[0]
            item_blocks = []
            for position, start in enumerate(item_starts):
                end = item_starts[position + 1] if position + 1 < len(item_starts) else section_end
                block = "".join(lines[start:end])
                title = block.splitlines()[0].removeprefix("    - title: ")
                item_blocks.append((title.casefold(), block))

            item_blocks.extend(
                (block.splitlines()[0].removeprefix("    - title: ").casefold(), block)
                for block in new_blocks
            )
            item_blocks.sort(key=lambda item: item[0])

            sorted_items = "".join(block for _, block in item_blocks)
            lines[item_start:section_end] = [sorted_items]
            with open(yaml_path, "w") as f:
                f.writelines(lines)
            logging.info(
                f"Updated {yaml_path} with {len(new_blocks)} alphabetized tutorial(s)."
            )
        except Exception as e:
            logging.error(f"Failed to update sidebar yaml: {e}")
            sys.exit(1)
    else:
        logging.info("No new tutorials found. Sidebar is already up-to-date.")

def main():
    parser = argparse.ArgumentParser(description="Synchronize tutorials from precice/tutorials to Hugo config.")
    parser.add_argument("--module-toml", required=True, help="Path to output the generated module TOML file.")
    parser.add_argument("--sidebar-yaml", required=True, help="Path to the tutorial_sidebar.yml file to update.")
    parser.add_argument("--repo", default="precice/tutorials", help="Target GitHub repository (default: precice/tutorials)")
    parser.add_argument("--branch", default="master", help="Target branch (default: master)")
    
    args = parser.parse_args()
    setup_logging()
    
    tree_data = fetch_github_tree(repo=args.repo, branch=args.branch)
    tutorials, images = discover_tutorials(tree_data)
    
    generate_module_toml(args.module_toml, tutorials, images)
    update_sidebar_yaml(args.sidebar_yaml, tutorials)

if __name__ == "__main__":
    main()
